import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className='p-4 md:p-16'>
          <div className='md:w-4/5 mx-auto'>
            <div className='flex justify-between'>
              <h1 className='text-base md:text-3xl text-center'>
                <Link href={'/todos'}>Todo Lists</Link>
              </h1>
              <div className='flex items-end'>
                <Link href={'/todos'} className='inline underline align-bottom text-xs md:text-sm'>
                  Todo一覧
                </Link>
                <Link
                  href={'/todos/new'}
                  className='inline ml-4 underline align-bottom text-xs md:text-sm'
                >
                  Todo作成
                </Link>
              </div>
            </div>

            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
